### ISSUE TITLE
Don't work in Server Side Rendering?

### ISSUE THREAD

**Issue by captainheart** [creativetimofficial/react-bootstrap-wizard#14]
I was going to render this component in server side and got this error.

```
ReferenceError: window is not defined
    at new ReactWizard (E:\ico-mern\node_modules\react-bootstrap-wizard\dist\index.js:41:13)
    at processChild (E:\ico-mern\node_modules\react-dom\cjs\react-dom-server.node.development.js:2095:14)
    at resolve (E:\ico-mern\node_modules\react-dom\cjs\react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (E:\ico-mern\node_modules\react-dom\cjs\react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (E:\ico-mern\node_modules\react-dom\cjs\react-dom-server.node.development.js:2354:19)
    at renderToString (E:\ico-mern\node_modules\react-dom\cjs\react-dom-server.node.development.js:2726:25)
```

**Comment by EINazare** [comment]
Hello there @captainheart ,

Thank you for your interest in using this product.
So from what i can see, there is a problem with the fact that we have in our product a window event listener. Window is a browser side object. I am not sure this product will ever be working on Server Side Rendering since we really need that event listener on the window object.
The problem is, that if the window resizes, the nav tabs would not resize, and we've added a window.resize event, and when that triggers, it also triggers the resize of the nav tabs. Not sure if you understand what i am trying to say.
Anyway, if you have any ideas of how we could do trigger the resize of the nav tabs - actually, they are not the nav tabs, it is a small component that goes over them, and that component has some in-line styles. And when the window resizes we need to change those inline styles. You can go ahead and look inside our code and if you figure out a way on how to change the styles of that component (it is called the moving tab), than we would really appreciate it.
When i'll have some spare time, I'll try and find out if there is something I can do here.

Best,
Manu

**Comment by captainheart** [comment]
Hi @EINazare !
Now I'm trying to figure it out.
When I've found a workaround, may I shoot you a Pull Request?
Or you may invite me as a collaborator.

**Comment by EINazare** [comment]
Hello again @captainheart ,

I think you should open a PR for the moment.
I am not the owner of the this repo and can't add you as collaborator.
Will ask creative-tim owner if you can be added as a collaborator.

Best,
Manu
